- hosts: localhost
  become: False
  collections:
    - tand0.ttl
  vars:
    pythoninterpreter: /mnt/d/gitwork/ansibletest/ansible/venv/bin/python3.12
    wsl2homework: /home/t-ando/work/collections/ansible_collections/tand0/ttl/
  tasks:
    - name: file copy (ansible tand0.ttl)
      copy:
        src: ../nextnextping/grammer/
        dest: collections/ansible_collections/tand0/ttl/plugins/module_utils

    - name: get version
      version:
      register: version
    - debug:
        msg: "version: {{ version.version }}.1"

    - lineinfile:
        path: collections/ansible_collections/tand0/ttl/galaxy.yml
        regexp: '^version:'
        line: 'version: "{{ version.version }}.1"'

    - name: file copy (local environment)
      copy:
        src: collections
        dest: /home/t-ando/work/

    - name: Execute ansible-test sanity
      command: ansible-test sanity --requirements --python-interpreter {{pythoninterpreter}} --skip-test import --skip-test validate-modules
      args:
        chdir: "{{wsl2homework}}"
      register: sanity_result
    - name: Execute ansible-test sanity debug
      debug:
        var: sanity_result.stdout_lines

    - name: Ceate tar gz file
      command: ansible-galaxy collection build . --force
      args:
        chdir: "{{wsl2homework}}"

    - name: file copy (local environment)
      copy:
        src: "{{wsl2homework}}tand0-ttl-{{version.version}}.1.tar.gz"
        dest: ../nextnextping/dist/
  
    - name: assert OK
      ttl:
        cmd: |
          result = 1
          assert 1 result
      register: ttl_output

    - name: assert NG
      ttl:
        cmd: |
          assert 0 result
          result = 1
      register: ttl_output
      ignore_errors: true
    - name: assert NG check
      fail:
      when: (ttl_output.failed == False) and (not ansible_check_mode)

    - name: result NG
      ttl:
        cmd: |
          result = 0
        ignore_result: False
      register: ttl_output
      ignore_errors: true
    - fail:
      when: (ttl_output.failed == False) and (not ansible_check_mode)

    - name: result NG but ignore_result is True
      ttl:
        cmd: |
          result = 0

    - name: ../test/0000_ok_test.ttl and param
      ttl:
        cmd: xxx = 1025
        filename: 0000_ok_test.ttl
        chdir: ../test
        ignore_result: False
      register: ttl_output
    - debug:
        msg: "{{ ttl_output }}"
    - name: param check
      fail:
      when: (not ansible_check_mode) and (ttl_output.value.xxx != 1025)
    - name: file check
      fail:
      when: (not ansible_check_mode) and (ttl_output.value.a != 6)

    - import_tasks:
        file: site_import.yml

