- hosts: localhost
  become: False
  collections:
    - tand0.ttl
  vars:
    pythoninterpreter: /mnt/d/gitwork/ansibletest/ansible/venv/bin/python3.12
    wsl2homework: /home/t-ando/work/collections/ansible_collections/tand0/ttl/
  tasks:
    - name: assert OK
      ttl:
        cmd: |
          result = 1
          assert 1 result
      register: ttl_output

    - name: assert NG
      ttl:
        cmd: |
          assert 0 result
          result = 1
      register: ttl_output
      ignore_errors: true
    - name: assert NG check
      fail:
      when: (ttl_output.failed == False) and (not ansible_check_mode)

    - name: result NG
      ttl:
        cmd: |
          result = 0
        ignore_result: False
      register: ttl_output
      ignore_errors: true
    - fail:
      when: (ttl_output.failed == False) and (not ansible_check_mode)

    - name: result NG but ignore_result is default(True)
      ttl:
        cmd: |
          result = 0

    - name: ../test/0000_ok_test.ttl and param
      ttl:
        cmd: xxx = 1025
        filename: 0000_ok_test.ttl
        chdir: ../test
        ignore_result: False
      register: ttl_output
    - debug:
        msg: "{{ ttl_output }}"
    - name: param check
      fail:
      when: (not ansible_check_mode) and (ttl_output.value.xxx != 1025)
    - name: file check
      fail:
      when: (not ansible_check_mode) and (ttl_output.value.a != 6)

    - name: "test: connect /cmd"
      ttl:
        cmd: |
          connect '/cmd'
          ;
          flushrecv
          sendln 'pwd'
          wait 'pwd'
          wait '$'
          ;
          flushrecv
          sendln 'ls'
          wait 'ls'
          wait '$'
      register: ttl_output
    - name: "test: connect /cmd"
      debug:
        var: ttl_output.stdout_lines
    - name: "test: start_date"
      debug:
        msg: "{{ttl_output.start}}"
    - name: "test: end_date"
      debug:
        msg: "{{ttl_output.end}}"
    - name: "test: delta"
      debug:
        msg: "{{ttl_output.delta}}"

    - name: include tasks
      include_tasks: site_import.yml

